### ISSUE TITLE
Broken up when working with redux-form

### ISSUE THREAD

**Issue by dynchen** [H2rmone/redux-async-loading#1]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It will broken up the application when working with redux-form.The following picture provides the detail.

![bug-detail](https://user-images.githubusercontent.com/3733854/41634411-2fd48808-7476-11e8-8773-8005e3f65d9a.jpeg)

Hope to fix it as soon as possible,thx.

**Comment by H2rmone** [comment]
Thanks for providing the bug, I fixed it with v0.1.1. Please update the version of `redux-async-loading`.
